// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGIds
{
        public const string achievement_addict = "CgkIobeXidUMEAIQCA"; // <GPGSID>
        public const string achievement_long_distance_runner = "CgkIobeXidUMEAIQCw"; // <GPGSID>
        public const string leaderboard_distance = "CgkIobeXidUMEAIQBw"; // <GPGSID>
        public const string achievement_power_surge = "CgkIobeXidUMEAIQDQ"; // <GPGSID>
        public const string achievement_fan_club = "CgkIobeXidUMEAIQCQ"; // <GPGSID>
        public const string achievement_sprinter = "CgkIobeXidUMEAIQAg"; // <GPGSID>
        public const string achievement_something_shiny = "CgkIobeXidUMEAIQAw"; // <GPGSID>
        public const string achievement_newbie = "CgkIobeXidUMEAIQAQ"; // <GPGSID>
        public const string achievement_jeweler = "CgkIobeXidUMEAIQDA"; // <GPGSID>
        public const string achievement_runner = "CgkIobeXidUMEAIQCg"; // <GPGSID>
        public const string achievement_i_feel_the_power = "CgkIobeXidUMEAIQBQ"; // <GPGSID>
        public const string achievement_overpowered = "CgkIobeXidUMEAIQDg"; // <GPGSID>
        public const string achievement_monster_slayer = "CgkIobeXidUMEAIQDw"; // <GPGSID>
        public const string achievement_gemology = "CgkIobeXidUMEAIQBA"; // <GPGSID>
        public const string leaderboard_best_score = "CgkIobeXidUMEAIQBg"; // <GPGSID>

}

